lualpeg: pass LDFLAGS (#4)
Pass LDFLAGS in the CC command so that lpeg.so symbols hash style
includes GNU_HASH. Fixes the following build error:

ERROR: lualpeg-1.0.2-r0 do_package_qa: QA Issue: File /usr/lib/lua/5.3/lpeg.so in package lualpeg doesn't have GNU_HASH (didn't pass LDFLAGS?) [ldflags]